{{- if eq $.Values.global.cluster_family "openshift" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: prometheus-pelorus
spec:
  port:
    targetPort: web-tls
  host: ""
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: prometheus-pelorus
    weight: 100
  wildcardPolicy: None
{{- end }}
