{{- define "exporters.buildconfig" }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    application: {{ .Release.Name}}
  name: {{ .Release.Name }}
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Release.Name }}:latest
  source:
    contextDir: {{ .source_context_dir | default "exporters/" }}
    git:
      ref: {{ .source_ref | default "v2.0.0" }}
      uri: {{ .source_url | default "https://github.com/konveyor/pelorus.git"}}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-39
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secretReference:
        name: github-secret
    type: GitHub
  - type: ConfigChange
  - type: ImageChange
{{- end }}
