{{- define "exporters.imagestream" }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
{{- end }}
