{{- define "exporters.route" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Release.Name }}
{{- end }}
