{{- define "exporters.service" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    k8s-app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    deploymentconfig: {{ .Release.Name }}
  type: ClusterIP
{{- end }}
