# permissions for end users to edit exporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exporter-editor-role
rules:
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - exporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - exporters/status
  verbs:
  - get
