# permissions for end users to edit failuretimeexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: failuretimeexporter-editor-role
rules:
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - failuretimeexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - failuretimeexporters/status
  verbs:
  - get
