# permissions for end users to edit pelorus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pelorus-editor-role
rules:
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - pelorus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - pelorus/status
  verbs:
  - get
