apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for pelorus.konveyor.io/v1alpha1, Kind: Pelorus
##
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - pelorus
  - pelorus/status
  - pelorus/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "integreatly.org"
  resources:
  - "grafanadashboards"
  - "grafanadatasources"
  - "grafanas"
- verbs:
  - "*"
  apiGroups:
  - "monitoring.coreos.com"
  resources:
  - "prometheuses"
  - "prometheusrules"
  - "servicemonitors"
- verbs:
  - "*"
  apiGroups:
  - "route.openshift.io"
  resources:
  - "routes"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "secrets"
  - "serviceaccounts"
  - "services"

##
## Rules for pelorus.konveyor.io/v1alpha1, Kind: CommitTimeExporter
##
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - committimeexporters
  - committimeexporters/status
  - committimeexporters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "monitoring.coreos.com"
  resources:
  - "servicemonitors"

##
## Rules for pelorus.konveyor.io/v1alpha1, Kind: DeployTimeExporter
##
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - deploytimeexporters
  - deploytimeexporters/status
  - deploytimeexporters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "monitoring.coreos.com"
  resources:
  - "servicemonitors"

##
## Rules for pelorus.konveyor.io/v1alpha1, Kind: FailureTimeExporter
##
- apiGroups:
  - pelorus.konveyor.io
  resources:
  - failuretimeexporters
  - failuretimeexporters/status
  - failuretimeexporters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "monitoring.coreos.com"
  resources:
  - "servicemonitors"

#+kubebuilder:scaffold:rules
