{{- define "exporters.deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .app_name }}
    application: {{ .app_name }}
  name: {{ .app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .app_name }}
      app: {{ .app_name }}
      deployment: {{ .app_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .app_name }}
        app: {{ .app_name }}
        deployment: {{ .app_name }}
        application: {{ .app_name}}
    spec:
      containers:
      - name: {{ .app_name }}
        image: {{ .app_name }}:latest
        imagePullPolicy: Always
      {{- if .env_from_secrets }}
        envFrom:
        {{- range .env_from_secrets }}  
        - secretRef:
            name: {{ . }}
        {{- end}}
      {{- end}}
        env:
{{- if .extraEnv }}
{{ toYaml .extraEnv | indent 8 }}
{{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
      serviceAccount: pelorus-exporter
{{- end }}
