{{- define "exporters.ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .app_name }}
  annotations:
    kubernetes.io/ingress.class: haproxy
  labels:
    app.kubernetes.io/name: {{ .app_name }}
spec:
  rules:
  - host: {{ .app_name }}.10.19.2.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .app_name }}
            port:
              number: 8080
{{- end }}