{{- define "exporters.service" -}}
{{- $cluster_family := get . "cluster_family" -}}
{{- with (get . "exporter") -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .app_name }}
    k8s-app: {{ .app_name }}
  name: {{ .app_name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .app_name }}
  {{- if eq $.cluster_family "openshift" }}
    deploymentconfig: {{ .app_name }}
  {{- else}}
    deployment: {{ .app_name }}
  {{- end }}
  type: ClusterIP
{{- end -}}
{{- end -}}
