name: Chart Lint
on:
  push:
    branches: [ master ]
    paths: 
      - 'charts/**'
      - 'lintconf.yaml'
      - '.github/workflows/chart-lint.yml'
      - 'exporters/requirements-dev.txt' # yamllint and yamale
      - Makefile
  pull_request:
    branches: [ master ]
    paths: 
      - 'charts/**'
      - 'lintconf.yaml'
      - '.github/workflows/chart-lint.yml'
      - 'exporters/requirements-dev.txt' # yamllint and yamale
      - Makefile

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Lint charts
        run: make chart-lint
