name: Integration Tests
on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exporters/requirements.txt
          pip install -r exporters/requirements-dev.txt
      - name: Start Mockoon in background
        run: docker run --name=mockoon -d --mount type=bind,source=$PWD/mocks/commitexporter_github.json,target=/data,readonly -p 3000:3000 mockoon/cli:latest -d /data --name openshift -p 3000
      - name: try until mockoon is ready
        run: |
          pip install httpie
          until curl -k https://localhost:3000/version; do echo "trying again in 1 second"; sleep 1; done
      - name: run commit exporter
        run: |
          export GIT_USER=gituser
          export GIT_TOKEN=gittoken
          export GIT_API=localhost:3000
          export LOG_LEVEL=DEBUG
          export NAMESPACES=basic-nginx-build,basic-nginx-dev,basic-nginx-stage,basic-nginx-prod
          export TLS_VERIFY=False
          pip install ./exporters
          python exporters/committime/app.py